### ISSUE TITLE
El padding en dispositivos móviles está mal en el Fieldset

### ISSUE THREAD

**Issue by LoweLeo** [selsa-inube/personas#408]
1. Revisar los valores que recibe el Fieldset en su padding para su versión tablet y móvil, ya que actualmente son diferentes con respecto al diseño del Figma

![imagen](https://github.com/selsa-inube/personas/assets/152199887/34efcea0-3fbb-4378-b745-7ec611dd87d8)
![imagen](https://github.com/selsa-inube/personas/assets/152199887/41d3dffb-3a3d-42b7-bef5-a4766f8da371)

Adicionalmente, revisar el Label que recibe el Fieldset este actualmente dice Dirección N°1, mientras que en los diseños del Figma dice Dirección de residencia

**Comment by Sebas3245** [comment]
Se esta resolviendo el tema del padding en dispositivos moviles, hay que tener en cuenta algo y es que el padding en el figma se cuenta desde la mitad del legend del fieldset:
![image](https://github.com/selsa-inube/personas/assets/55991750/ecd5fad4-d1a5-40fa-b30e-aac566a85dd0)

Mientras que en el HTML del proyecto el fieldset cuenta el padding desde la parte de arriba del fieldset:
![image](https://github.com/selsa-inube/personas/assets/55991750/d29ff57a-eceb-4c0e-b46f-0c9aa2a2ab4a)


Por ese motivo colocamos un padding-top inferior al del padding-bottom ya que, si los dejamos iguales, el legend por defecto añade un espacio adicional entre el mismo y la parte superior del contenido interior del fieldset (esto lo hace por defecto HTML) por lo tanto hacemos ese cálculo dejando menor el padding-top
