### ISSUE TITLE
Cambiar ruta y folder de `<Credit />`

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/personas#46]
- [x] Sigamos usando my-credits/ para todo lo que tenga que ver con los créditos de un cliente. Así que para este caso habría que ajustar el router y colocar my-credits/:credit_id
- [x] Guardar la página dentro de pages/admin/myCredits. Dentro de myCredits tendríamos al final Credit, Movements, Amortization y demás páginas que sean propias de la consulta de créditos.

**Nota**: estoy intentando ingresar a https://personas-inube.vercel.app/credit/5 y aparece 404. Hacer el cambio en el router y probar que pueda acceder a la página así esté en blanco.

**Comment by Sebas3245** [comment]
solved in PR #40
