### ISSUE TITLE
the boxAttribute component in my-credits is overflowing

### ISSUE THREAD

**Issue by novadeveloper14** [selsa-inube/personas#84]
el componente boxAttribute en la pagina my-credits se esta desbordando.

![image](https://github.com/selsa-inube/personas/assets/87447257/824654e0-a9e1-4ee0-b364-c256f86927b3)

**Comment by Sebas3245** [comment]
¿En qué dimensiones sucede esto?

**Comment by novadeveloper14** [comment]
por debajo de 750px
