### ISSUE TITLE
Cambiar orden en apagado de columnas de datos en tablas de movimientos

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/personas#95]
Las columnas de datos de estas tablas deberían apagarse en este orden:
1. Referencia
2. Descripción
3. Fecha

Es decir, en el caso mobile, el usuario por lo menos debería estar viendo la fecha.

**Comment by Sebas3245** [comment]
Este ajuste se propone en el issue #85 en el cual se planteó corregir las prioridades
